import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import ToastClientProvider from '@/providers/toastProvider';
import { ThemeProvider } from '@/providers/themeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-white text-black dark:bg-neutral-900 dark:text-white">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ToastClientProvider />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
