import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

// Styles:
import './globals.css';
import { cn } from '@/utils';

// Providers:
import { ToastProvider } from 'react-bell';

// Fonts:
const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

// Metadata:
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('font-sans antialiased', fontSans.variable)}>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
